### ISSUE TITLE
Package test failing

### ISSUE THREAD

**Issue by ikizhvatov** [Riscure/Jlsca#4]
ParallelIncrementalCPATestWithInterval() fails with EOFError.

**Comment by ceesb** [comment]
Cannot repeat on my end, you still have the stack trace?

**Comment by ikizhvatov** [comment]
With the newest commit that error is not there any more. But there is another error: in phase 14 of the SHA1 attack test the recovered key does not match the known key.

**Comment by ceesb** [comment]
Fixed in @da5cd2a5268fe00f385a88a2e03fc756d991539a
